In [1]:
import pandas as pd

## Revision de data

Se revisan los datos del archivo csv y se acondicionan para trabajar posteriormente en Streamlit.

In [2]:
df_cars = pd.read_csv("./data/vehiculos_electricos_hibridos.csv")

In [3]:
# Reemplazar nombres de las columnas
df_cars.rename(columns={"AÑO_REGISTRO":"ANIO_REGISTRO"},inplace=True)

In [4]:
# Retirar los NaN de una columna:
df_cars["MODALIDAD"].fillna("", inplace=True)

In [5]:
# Se quitan los nan y se reemplaza de float por integer.
list_to_change = [
    "CILINDRAJE",
    "CAPACIDAD_CARGA",
    "CAPACIDAD_PASAJEROS",
    "PESO",
    "POTENCIA",
    "EJES"
]

for column_name in list_to_change:
    df_cars[column_name] = pd.to_numeric(df_cars[column_name], errors='coerce').fillna(0)
    df_cars[column_name] = df_cars[column_name].astype("int64")

df_cars.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56545 entries, 0 to 56544
Data columns (total 22 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   COMBUSTIBLE          56545 non-null  object
 1   ESTADO               56545 non-null  object
 2   MODELO               56545 non-null  int64
 3   FECHA_REGISTRO       56545 non-null  object
 4   ANIO_REGISTRO        56545 non-null  int64
 5   CLASIFICACION        56545 non-null  object
 6   CLASE                56545 non-null  object
 7   SERVICIO             56545 non-null  object
 8   MARCA                56545 non-null  object
 9   LINEA                56545 non-null  object
 10  CARROCERIA           56545 non-null  object
 11  CILINDRAJE           56545 non-null  int64
 12  MODALIDAD            56545 non-null  object
 13  ORGANISMO_TRANSITO   56545 non-null  object
 14  MUNICIPIO            56545 non-null  object
 15  DEPARTAMENTO         56545 non-null  object
 16  CAPACIDAD_CARGA      56545 non-null  int64
 17  CAPACIDAD_PASAJEROS  56545 non-null  int64
 18  PESO                 56545 non-null  int64
 19  POTENCIA             56545 non-null  int64
 20  EJES                 56545 non-null  int64
 21  CANTIDAD             56545 non-null  int64
dtypes: int64(9), object(13)
memory usage: 9.5+ MB

In [6]:
df_cars.sample(5)

,COMBUSTIBLE,ESTADO,MODELO,FECHA_REGISTRO,ANIO_REGISTRO,CLASIFICACION,CLASE,SERVICIO,MARCA,LINEA,...,MODALIDAD,ORGANISMO_TRANSITO,MUNICIPIO,DEPARTAMENTO,CAPACIDAD_CARGA,CAPACIDAD_PASAJEROS,PESO,POTENCIA,EJES,CANTIDAD
31845,GASO ELEC,ACTIVO,2022,07/14/2022 12:00:00 AM,2022,AUTOMOVIL,CAMIONETA,Particular,FORD,ESCAPE SEL,...,PASAJEROS,SDM - BOGOTA D.C.,BOGOTA,Bogota D.C.,0,0,2075,200,2,1
2530,ELECTRICO,ACTIVO,2014,06/11/2014 12:00:00 AM,2014,MOTO,MOTOCICLETA,Particular,ENERGY MOTION,MLY A,...,,INST TTOyTTE DE CERETE,CERETE,Cordoba,0,0,0,0,0,1
16483,GASO ELEC,ACTIVO,2020,11/10/2020 12:00:00 AM,2020,AUTOMOVIL,CAMIONETA,Particular,FORD,ESCAPE SE HEV,...,,STRIA DE TTOyTTE MEDELLIN,MEDELLIN,Antioquia,0,0,2075,163,2,1
2307,ELECTRICO,ACTIVO,2015,07/22/2015 12:00:00 AM,2015,MOTO,MOTOCICLETA,Particular,ENERGY MOTION,MNY,...,,AGENCIA DE SEGURIDAD VIAL ANTIOQUIA/GUARNE,GUARNE,Antioquia,0,0,0,0,0,1
12550,GASO ELEC,ACTIVO,2023,09/27/2022 12:00:00 AM,2022,AUTOMOVIL,AUTOMOVIL,Particular,TOYOTA,COROLLA,...,,SECRETARIA DE MOVILIDAD MUNICIPAL DE CHIA,CHIA,Cundinamarca,0,0,1825,126,2,1

In [7]:
# Guardar el archivo:
df_cars.to_csv("./data/electric_cars.csv", index=False)

In [8]:
df_cars.groupby("MUNICIPIO")["CANTIDAD"].count()

MUNICIPIO
ACACIAS      11
AGUADAS       2
AGUAZUL       3
ALVARADO      7
ANDALUCIA     3
             ..
VILLETA       2
YOPAL        80
YOTOCO       12
YUMBO         2
ZIPAQUIRA    69
Name: CANTIDAD, Length: 176, dtype: int64